
import { createClient } from '@supabase/supabase-js'
import { readFileSync, readdirSync } from 'fs'
import { join } from 'path'
import dotenv from 'dotenv'

// Load environment variables
dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseServiceKey || supabaseUrl === 'your-supabase-url') {
  console.error('Please set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

const DATA_DIR = join(process.cwd(), 'data')

async function migrate() {
  const files = readdirSync(DATA_DIR).filter(f => f.endsWith('.json'))

  for (const file of files) {
    const type = file.replace('.json', '')
    const filePath = join(DATA_DIR, file)
    const rawData = JSON.parse(readFileSync(filePath, 'utf-8'))

    console.log(`\n--- Migrating ${type} ---`)

    let dataToInsert = []

    // Map JSON structure to table data - omit 'id' if 'GENERATED ALWAYS AS IDENTITY' is used
    if (type === 'experience') {
      dataToInsert = rawData.experiences.map((exp: any) => ({
        // id: exp.id, // Omit to let Supabase generate
        position: exp.position,
        company: exp.company,
        start_date: exp.startDate,
        end_date: exp.endDate,
        is_current: exp.isCurrent,
        description: exp.description
      }))
    } else if (type === 'goals') {
      dataToInsert = rawData.goals.map((g: any) => ({
        title: g.title,
        description: g.description,
        timeline: g.timeline
      }))
    } else if (type === 'images') {
      dataToInsert = rawData.images // Has string ID, safe to insert
    } else if (type === 'introduction') {
      // Introduction is a single row table, ID is predefined as 1
      dataToInsert = [{
        id: 1, 
        full_name: rawData.fullName,
        title: rawData.title,
        specializations: rawData.specializations,
        bio: rawData.bio,
        email: rawData.email,
        phone: rawData.phone,
        location: rawData.location,
        profile_image: rawData.profileImage
      }]
    } else if (type === 'prof_skills') {
      dataToInsert = rawData.map((skill: any) => ({
        title: skill.title,
        description: skill.desc,
        badges: skill.badges
      }))
    } else if (type === 'projects') {
      dataToInsert = rawData.projects.map((proj: any) => ({
        title: proj.title,
        description: proj.description,
        role: proj.role,
        duration: proj.duration,
        budget: proj.budget,
        team: proj.team,
        image: proj.image,
        outcomes: proj.outcomes
      }))
    } else if (type === 'skills') {
      dataToInsert = rawData.skills.map((s: any) => ({
        name: s.name,
        proficiency: s.proficiency,
        category: s.category
      }))
    } else if (type === 'inquiries') {
      dataToInsert = Array.isArray(rawData) ? rawData : []
    }

    if (dataToInsert.length > 0) {
      // For tables that generate IDs, we just insert.
      // For introduction or images, we can upsert.
      const isUpsert = type === 'introduction' || type === 'images'

      let error;
      if (isUpsert) {
         const result = await supabase.from(type).upsert(dataToInsert)
         error = result.error
      } else {
         // Clear table first to avoid duplicates during multiple test runs
         await supabase.from(type).delete().neq('id', -1);
         const result = await supabase.from(type).insert(dataToInsert)
         error = result.error
      }

      if (error) {
        console.error(`Error migrating ${type}:`, error.message)
      } else {
        console.log(`Successfully migrated ${type}`)
      }
    } else {
      console.log(`No data to migrate for ${type}`)
    }
  }
}

migrate()
  .then(() => console.log('\nMigration finished'))
  .catch(err => console.error('\nMigration failed:', err))

/*
-- SQL SCHEMA (Run this in Supabase SQL Editor first)

-- Create experience table
CREATE TABLE IF NOT EXISTS experience (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  position TEXT,
  company TEXT,
  start_date DATE,
  end_date DATE,
  is_current BOOLEAN,
  description TEXT
);

-- Create goals table
CREATE TABLE IF NOT EXISTS goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  description TEXT,
  timeline TEXT
);

-- Create images table
CREATE TABLE IF NOT EXISTS images (
  id TEXT PRIMARY KEY,
  name TEXT,
  url TEXT,
  type TEXT
);

-- Create inquiries table
CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create introduction table (single row)
CREATE TABLE IF NOT EXISTS introduction (
  id INT PRIMARY KEY DEFAULT 1,
  full_name TEXT,
  title TEXT,
  specializations TEXT[],
  bio TEXT,
  email TEXT,
  phone TEXT,
  location TEXT,
  profile_image TEXT,
  CONSTRAINT single_row CHECK (id = 1)
);

-- Create prof_skills table
CREATE TABLE IF NOT EXISTS prof_skills (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  description TEXT,
  badges TEXT[]
);

-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  description TEXT,
  role TEXT,
  duration TEXT,
  budget TEXT,
  team TEXT,
  image TEXT,
  outcomes TEXT[]
);

-- Create skills table
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  proficiency INT,
  category TEXT
);
*/
